# Generated by Django 5.2.1 on 2025-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0001_initial'),
    ]

    operations = [
    ]
