# Generated by Django 5.2.1 on 2025-06-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_smart', '0002_auto_20250606_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField()),
                ('descricao', models.TextField()),
                ('ni', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=20)),
                ('unidade_med', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api_smart.ambientes')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api_smart.sensores')),
            ],
        ),
    ]
