# Generated by Django 5.1.7 on 2025-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulos', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('editora', models.CharField(max_length=20)),
            ],
        ),
    ]
